# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Revoked JWT tokens Retrieval API
  description: This API allows you to fetch the signatures and expiry time of revoked JWT tokens.
  version: "1.0.0"
# the domain of the service
host: wso2.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /revokedjwt:
    get:
      summary: JTIs of revoked jwt tokens
      description: |
        This will provide access to JTIs of revoked JWT tokens in database.
      parameters:
        - name : query
          in: query
          description: |
            **Search condition**.

            You can search for an application by specifying the name as "query" attribute.

            Eg.
            "app1" will match an application if the name is exactly "app1".

            Currently this does not support wildcards. Given name must exactly match the application name.
          type: string
      tags:
        - Shops
      responses:
        200:
          description: An array of shops around you
          schema:
            type: array
            items:
              $ref: '#/definitions/RevokedJWTList'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  RevokedJWTList:
    type: array
    items:
      $ref: '#/definitions/RevokedJWT'

  RevokedJWT:
    properties:
      jwt_signature:
        type: string
        description: signature of the JWT token.
      expiry_time:
        type: integer
        format: int64
        description: expiry timestamp.

  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string